/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/hi/gopher': RouteRecordInfo<
      '/hi/gopher',
      '/hi/gopher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/vue': RouteRecordInfo<
      '/hi/vue',
      '/hi/vue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/no-ssr-fetch': RouteRecordInfo<
      '/no-ssr-fetch',
      '/no-ssr-fetch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/protected': RouteRecordInfo<
      '/protected',
      '/protected',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/seo-demo': RouteRecordInfo<
      '/seo-demo',
      '/seo-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/session-demo': RouteRecordInfo<
      '/session-demo',
      '/session-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/slow-ssr': RouteRecordInfo<
      '/slow-ssr',
      '/slow-ssr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/hi/gopher.vue': {
      routes:
        | '/hi/gopher'
      views:
        | never
    }
    'src/pages/hi/vue.vue': {
      routes:
        | '/hi/vue'
      views:
        | never
    }
    'src/pages/no-ssr-fetch.vue': {
      routes:
        | '/no-ssr-fetch'
      views:
        | never
    }
    'src/pages/protected.vue': {
      routes:
        | '/protected'
      views:
        | never
    }
    'src/pages/seo-demo.vue': {
      routes:
        | '/seo-demo'
      views:
        | never
    }
    'src/pages/session-demo.vue': {
      routes:
        | '/session-demo'
      views:
        | never
    }
    'src/pages/slow-ssr.vue': {
      routes:
        | '/slow-ssr'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
